#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ_to_SQL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="oa")]
	public partial class dblimaganDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCalendar(Calendar instance);
    partial void UpdateCalendar(Calendar instance);
    partial void DeleteCalendar(Calendar instance);
    #endregion
		
		public dblimaganDataContext() : 
				base(global::LINQ_to_SQL.Properties.Settings.Default.oaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dblimaganDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dblimaganDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dblimaganDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dblimaganDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Calendar> Calendar
		{
			get
			{
				return this.GetTable<Calendar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calendar")]
	public partial class Calendar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UID;
		
		private string _EID;
		
		private string _EName;
		
		private string _STime;
		
		private string _ETime;
		
		private string _CTime;
		
		private System.DateTime _MTime;
		
		private int _LogicDelete;
		
		private string _MEMO;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUIDChanging(string value);
    partial void OnUIDChanged();
    partial void OnEIDChanging(string value);
    partial void OnEIDChanged();
    partial void OnENameChanging(string value);
    partial void OnENameChanged();
    partial void OnSTimeChanging(string value);
    partial void OnSTimeChanged();
    partial void OnETimeChanging(string value);
    partial void OnETimeChanged();
    partial void OnCTimeChanging(string value);
    partial void OnCTimeChanged();
    partial void OnMTimeChanging(System.DateTime value);
    partial void OnMTimeChanged();
    partial void OnLogicDeleteChanging(int value);
    partial void OnLogicDeleteChanged();
    partial void OnMEMOChanging(string value);
    partial void OnMEMOChanged();
    #endregion
		
		public Calendar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string UID
		{
			get
			{
				return this._UID;
			}
			set
			{
				if ((this._UID != value))
				{
					this.OnUIDChanging(value);
					this.SendPropertyChanging();
					this._UID = value;
					this.SendPropertyChanged("UID");
					this.OnUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EID
		{
			get
			{
				return this._EID;
			}
			set
			{
				if ((this._EID != value))
				{
					this.OnEIDChanging(value);
					this.SendPropertyChanging();
					this._EID = value;
					this.SendPropertyChanged("EID");
					this.OnEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EName
		{
			get
			{
				return this._EName;
			}
			set
			{
				if ((this._EName != value))
				{
					this.OnENameChanging(value);
					this.SendPropertyChanging();
					this._EName = value;
					this.SendPropertyChanged("EName");
					this.OnENameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STime", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string STime
		{
			get
			{
				return this._STime;
			}
			set
			{
				if ((this._STime != value))
				{
					this.OnSTimeChanging(value);
					this.SendPropertyChanging();
					this._STime = value;
					this.SendPropertyChanged("STime");
					this.OnSTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ETime", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ETime
		{
			get
			{
				return this._ETime;
			}
			set
			{
				if ((this._ETime != value))
				{
					this.OnETimeChanging(value);
					this.SendPropertyChanging();
					this._ETime = value;
					this.SendPropertyChanged("ETime");
					this.OnETimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTime", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CTime
		{
			get
			{
				return this._CTime;
			}
			set
			{
				if ((this._CTime != value))
				{
					this.OnCTimeChanging(value);
					this.SendPropertyChanging();
					this._CTime = value;
					this.SendPropertyChanged("CTime");
					this.OnCTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MTime", DbType="DateTime NOT NULL")]
		public System.DateTime MTime
		{
			get
			{
				return this._MTime;
			}
			set
			{
				if ((this._MTime != value))
				{
					this.OnMTimeChanging(value);
					this.SendPropertyChanging();
					this._MTime = value;
					this.SendPropertyChanged("MTime");
					this.OnMTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogicDelete", DbType="Int NOT NULL")]
		public int LogicDelete
		{
			get
			{
				return this._LogicDelete;
			}
			set
			{
				if ((this._LogicDelete != value))
				{
					this.OnLogicDeleteChanging(value);
					this.SendPropertyChanging();
					this._LogicDelete = value;
					this.SendPropertyChanged("LogicDelete");
					this.OnLogicDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMO", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string MEMO
		{
			get
			{
				return this._MEMO;
			}
			set
			{
				if ((this._MEMO != value))
				{
					this.OnMEMOChanging(value);
					this.SendPropertyChanging();
					this._MEMO = value;
					this.SendPropertyChanged("MEMO");
					this.OnMEMOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}





	}
}
#pragma warning restore 1591
